### ISSUE TITLE
exportCVS for Downtime fails: Uncaught ReferenceError, ExportCSV is not defined

### ISSUE THREAD

**Issue by tuhs1985** [keyneston/vttmud#14]
```
Attempt to export downtime fails.  nothing observed while exporting, checking console reveals this:
framework-af27a8b8615822a5.js:9 Uncaught ReferenceError: exportCSV is not defined
    at onClick (downtime-73fe8cf69027a243.js:1:21437)
    at Object.eU (framework-af27a8b8615822a5.js:9:14912)
    at eH (framework-af27a8b8615822a5.js:9:15066)
    at framework-af27a8b8615822a5.js:9:33374
    at re (framework-af27a8b8615822a5.js:9:33473)
    at rn (framework-af27a8b8615822a5.js:9:33887)
    at framework-af27a8b8615822a5.js:9:39345
    at oP (framework-af27a8b8615822a5.js:9:96345)
    at eF (framework-af27a8b8615822a5.js:9:14046)
    at ro (framework-af27a8b8615822a5.js:9:35178)
onClick @ downtime-73fe8cf69027a243.js:1
eU @ framework-af27a8b8615822a5.js:9
eH @ framework-af27a8b8615822a5.js:9
(anonymous) @ framework-af27a8b8615822a5.js:9
re @ framework-af27a8b8615822a5.js:9
rn @ framework-af27a8b8615822a5.js:9
(anonymous) @ framework-af27a8b8615822a5.js:9
oP @ framework-af27a8b8615822a5.js:9
eF @ framework-af27a8b8615822a5.js:9
ro @ framework-af27a8b8615822a5.js:9
nU @ framework-af27a8b8615822a5.js:9
nD @ framework-af27a8b8615822a5.js:9
```

Referenceing this: 

![image](https://user-images.githubusercontent.com/77306309/235373913-6fbf4df0-7803-4896-a94f-90a9347fa77a.png)

**Comment by keyneston** [comment]
This should be fixed. Can you give it a try and confirm @tuhs1985?

**Comment by keyneston** [comment]
Tuhs confirmed this is fixed via discord.
