### ISSUE TITLE
Image uploads aren't working

### ISSUE THREAD

**Issue by keyneston** [keyneston/vttmud#20]
Reported by @tuhs1985.

```
site.webmanifest:1     Failed to load resource: the server responded with a status of 404 ()
site.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
site.webmanifest:1     Failed to load resource: the server responded with a status of 404 ()
[id]-d2a9fee152d31a63.js:1 Uncaught ReferenceError: setSrc is not defined
    at HTMLInputElement.<anonymous> ([id]-d2a9fee152d31a63.js:1:5267)
(anonymous) @ [id]-d2a9fee152d31a63.js:1
[id]-d2a9fee152d31a63.js:1 Uncaught ReferenceError: setSrc is not defined
    at HTMLInputElement.<anonymous> ([id]-d2a9fee152d31a63.js:1:5267)
(anonymous) @ [id]-d2a9fee152d31a63.js:1
```

![image](https://user-images.githubusercontent.com/39023/236240277-0668d07a-8a0f-4c1f-b540-11255d889208.png)

**Comment by keyneston** [comment]
From development build:

```
Unhandled Runtime Error

ReferenceError: setSrc is not defined
Source

pages/character/[id]/index.tsx (123:8) @ setSrc
```

**Comment by keyneston** [comment]
Tuhs confirmed this is fixed via discord.
